github: [Repository metadata]
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "1..3"
highlighter: rouge
permalink: pretty

# This variable controls changes the behaviour of the banner in
# `_includes/version_warning.md`. When generating documentation
# for a release this should be set to true.
is_release: false

# When doing a release make sure you exclude the releases folder by replacing
# the `exclude` declaration with the version that is currently commented out.
#
# It would be nice if we could just do the right thing if `is_release` is set to
# `true` but we can't do this in YAML.
# exclude: ['README.md', 'COPYING', 'Gemfile', 'Gemfile.lock', 'releases']
exclude: ['README.md', 'COPYING', 'Gemfile', 'Gemfile.lock']

plugins:
- jekyll-sitemap

project_title: KLEE
current_version: 2.2
repository: https://github.com/klee/klee
